version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: km
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 9001:5432