spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
---
spring:
  profiles:
    active: real
  datasource:
    url: jdbc:postgresql://localhost:9001/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port : 8081

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:9001/postgres
    username: km
    password: postgres
server:
  port : 8001