version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    volumes:
      - ./data:/var/jenkins_home
    ports:
      - 9002:8080
      - 50000:50000
